# -*- coding: utf-8 -*-
"""California_insights.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11GNAhuTjeCgAqAcIaepjrK_QtKjjwU_7
"""

# https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing

from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

dataset = fetch_california_housing()

print(dataset.DESCR)

print(dataset)

x = dataset['data'] [..., 0:1]
y = dataset['target']

plt.scatter(x[..., 0], y)
plt.xlabel('HouseAge')
plt.ylabel('MedInc')

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

print(x_train.shape, x_test.shape)

model = LinearRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

plt.scatter(x[..., 0], y)
plt.plot(x_test, y_pred, color='red')
plt.xlabel('HouseAge')
plt.ylabel('MedInc')

w = model.coef_
b = model.intercept_
print(w, b)

print(y_pred[0], w*x_test[0] + b)

r2_s = r2_score(y_test, y_pred)
mse_err = mean_squared_error(y_test, y_pred)

print(r2_s, mse_err)

